# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.10
        auth:
          username: jriccardi
          password: $DOCKERHUB_PASSWORD
        environment:
          MIX_ENV: test
      - image: circleci/postgres:latest
        auth:
          username: jriccardi
          password: $DOCKERHUB_PASSWORD 
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: dungeon_generator
          POSTGRES_PASSWORD:

    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: ["_build"]
      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
      - store_test_results:
          path: _build/test/lib/dungeon_generator